# Generated by Django 3.1 on 2020-09-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Man',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('contact', models.CharField(max_length=11, null=True, unique=True)),
                ('address', models.CharField(max_length=300, null=True, unique=True)),
                ('salary', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
